source'https://github.com/CocoaPods/Specs.git'

platform:ios,'11.0'

inhibit_all_warnings!

target 'ChaosComponent' do
   pod 'AFNetworking', '>3.0'
   pod "BeeHive"
  # pod 'KJExtensionHandler'
   pod 'FMDB'
   pod 'SDWebImage'
   pod 'Alamofire'
   pod 'ObjectMapper'
   pod 'SwiftyJSON'
   pod 'Moya'
   pod 'SnapKit'  #相当于
   pod 'MJRefresh'
   pod 'JKSwiftExtension'
   pod 'KRProgressHUD'
end
