source'https://github.com/CocoaPods/Specs.git'

platform:ios,'11.0'

inhibit_all_warnings!

def testing_pods
    pod 'Quick', '~>1.0.0'
    pod 'Nimble', '~>5.0.0'
end

target 'ChaosComponentTests' do
    testing_pods
end


target 'ChaosComponent' do
   pod 'AFNetworking', '>3.0'
   pod "BeeHive"
   #pod 'KJExtensionHandler'
   pod 'FMDB'
   pod 'SDWebImage'
   pod 'Alamofire'
   pod 'ObjectMapper'
   pod 'SwiftyJSON'
   pod 'Moya'
   pod 'SnapKit'  #相当于
   pod 'MJRefresh'
   pod 'JKSwiftExtension'
   pod 'KRProgressHUD'
 #  pod 'lottie-ios'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
